version: "2"

services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.4-debian-10
    environment:
      MONGO_INITDB_ROOT_USERNAME: chozoi
      MONGO_INITDB_ROOT_PASSWORD: zoiohc
      MONGODB_DATABASE: cz-crawl-data

    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/chozoi/mongodb"

  app:
    container_name: ecommerce-crawler
    build: .
    # image: "ecommerce-crawler:v1"
    environment:
      - PORT=3003
      - MONGODB_URI=mongodb://mongodb:27017/cz-crawl-data
      - SHOPEE_API=http://shopee.vn/api
    ports:
      - "3003:3003"

    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local
