version: "2"

services:
  # redis:
  #   container_name: cache
  #   image: 'docker.io/bitnami/redis:6.0-debian-10'
  #   environment:
  #     # ALLOW_EMPTY_PASSWORD is recommended only for development.
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  #   ports:
  #     - '6379:6379'
  #   expose:
  #        - 6379
  #   volumes:
  #     - 'redis_data:/bitnami/redis/data'

  mongodb:
    image: docker.io/bitnami/mongodb:4.4-debian-10
    environment:
      MONGO_INITDB_ROOT_USERNAME: chozoi
      MONGO_INITDB_ROOT_PASSWORD: zoiohc
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/chozoi/mongodb"

volumes:
  # redis_data:
  #   driver: local

  mongodb_data:
    driver: local
